api/urls.py
from rest_framework import routers
from .views import ImageViewSet, TemplateViewSet, TransactionViewSet

router = routers.DefaultRouter();
router.register(r'template', TemplateViewSet)
router.register(r'image', ImageViewSet)
router.register(r'transaction', TransactionViewSet)

myopencv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static

from api.urls import router as api_router

from .settings import MEDIA_ROOT, MEDIA_URL
from django.views.static import serve

urlpatterns = [
    # admin を有効にする
    url(r'^admin/', admin.site.urls),

    # template
    url(r'^template/', include('template.urls', namespace='template')),

    # API
    url(r'^api/', include(api_router.urls)),

    # link: http://stackoverflow.com/questions/34727928/django-1-10-urls-deprecation
    url(r'^data/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

template/urls.py
from django.conf.urls import url
from template import views


urlpatterns = [
    # テンプレート
    url(r'^$', views.template_list, name='template_list'),  # 一覧
    url(r'^create/$', views.template_update, name='template_create'),  # 登録
    url(r'^update/(?P<id>\d+)/$', views.template_update, name='template_update'),  # 修正
    url(r'^delete/(?P<id>\d+)/$', views.template_delete, name='template_delete'),  # 削除

    # 画像
    url(r'^update/(?P<id>\d+)/upload$', views.image_upload, name='image_upload'),  # 修正
    url(r'^image/delete/(?P<id>\d+)/$', views.image_delete, name='image_delete'),  # 削除

    #
    url(r'^transaction$', views.transaction_list, name='transaction_list'),  # 一覧
    url(r'^transaction/create/$', views.transaction_create, name='transaction_create'),  # 登録

]

template/templates/template/list.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}
{% load fontawesome %}

{% block title %}テンプレート一覧{% endblock title %}


{% block content %}
    <h3 class="page-header">テンプレート一覧</h3>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "info" %}
                <div class="alert alert-success">
                    <a class="close" data-dismiss="alert">{% fontawesome_icon 'remove'  %}</a>
                   {{ message }}
                </div>
            {% endif %}
             {% if message.tags == "error" %}
                <div class="alert alert-danger">
                    <a class="close" data-dismiss="alert">{% fontawesome_icon 'remove'  %}</a>
                   {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}


    <a href="{% url 'template:template_create' %}" class="btn btn-success">テンプレート登録  {% fontawesome_icon 'caret-right'  %}</a>

    {% if templates %}
        <table class="table table-striped table-hover table-bordered">
          <thead>
            <tr>
              <th>＃</th>
              <th>名前</th>
              <th>メモ</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>

            {% for item in templates %}
            <tr>
              <td>{{ forloop.counter }} </td>
              <td>{{ item.name }}</td>
              <td>{{ item.memo }}</td>
              <td class="operation">
                <a href="{% url 'template:template_update' id=item.id %}" class="btn btn-sm btn-warning">修正 {% fontawesome_icon 'edit'  %}</a>
                <a href="{% url 'template:template_delete' id=item.id %}" class="btn btn-sm btn-danger" id="deleteBtn{{ item.id }}">削除 {% fontawesome_icon 'trash'  %}</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <div id="dialog-confirm" title="テンプレート削除確認">
          <p><span class="ui-icon ui-icon-alert" ></span>テンプレートを削除します。よろしいでしょうか?</p>
        </div>


    {% endif %}
    <script>
          $(function(){
            //　モーダル初期設定
            $('#dialog-confirm').dialog({
                autoOpen: false,  // 自動でオープンしない
                modal: true,      // モーダル表示する
                resizable: false, // リサイズしない
                draggable: false, // ドラッグしない
                show: "clip",     // 表示時のエフェクト
                hide: "fade",      // 非表示時のエフェクト
                buttons: {
                    "確認": function() {
                        location.href=target_url;
                    },
                    "閉じる": function() {
                        $( this ).dialog( "close" );
                    }
                }
            });

            // .selecter クリック時にモーダル表示
            $("[id^=deleteBtn]").on("click",function(){
                target_url = $(this).attr("href");
                $('#dialog-confirm').dialog('open');
                return false;
            });
        });
    </script>
{% endblock content %}

template/templates/template/update.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}
{% load fontawesome %}

{% block title %}テンプレート編集{% endblock title %}

{% block content %}
    {% if id %}
    <h3 class="page-header">テンプレート変更</h3>
    <a href="{% url 'template:template_list' %}" class="btn btn-default btn-sm">{% fontawesome_icon 'arrow-left'  %} 戻る </a>
    <form action="{% url 'template:template_update' id=id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <h3 class="page-header">テンプレート登録</h3>
    <a href="{% url 'template:template_list' %}" class="btn btn-default btn-sm">{% fontawesome_icon 'arrow-left'  %} 戻る </a>
    <form action="{% url 'template:template_create' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      <!--{{ form|bootstrap_horizontal }}-->
        <section class="form-box">
            <fieldset>
                <p><span class="required">[*]は必須入力項目です。</span></p>
            {% for field in form %}
                {% if field.errors %}
                    <div class="control-group error">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">{{ field }}
                            <span class="help-inline">
                                {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="control-group">
                        <label class="control-label">{{ field.label }}<span class="required">[*]</span></label>
                        <div class="controls">{{ field }}
                            {% if field.help_text %}
                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
             {% if not id %}
                 <div class="operation">
                    <p><button type="submit" class="btn btn btn-success">{% fontawesome_icon 'save'  %} テンプレートを登録する</button></p>
                  </div>
              {% endif %}
            </fieldset>
        </section>

    {% if id %}
        <h4 class="page-header">テンプレート画像一覧</h4>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div class="alert alert-success">
                        <a class="close" data-dismiss="alert">{% fontawesome_icon 'remove'  %}</a>
                       {{ message }}
                    </div>
                {% endif %}
                 {% if message.tags == "error" %}
                    <div class="alert alert-danger">
                        <a class="close" data-dismiss="alert">{% fontawesome_icon 'remove'  %}</a>
                       {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <a href="{% url 'template:image_upload' id=id %}" class="btn btn-sm btn-success">テンプレート画像登録  {% fontawesome_icon 'caret-right'  %}</a>
        {% if images %}
            <div class="controls">
                <table class="table table-striped table-hover table-bordered">
                  <thead>
                    <tr>
                      <!--<th>ID</th>-->
                        <th>画像</th>
                        <th>名称</th>
                        <th>順位</th>
                        <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for image in images %}
                    <tr>
                      <!--<td>{{ image.id }}</td>-->
                      <td>
                          <a data-fancybox="gallery" href="{{ image.path.url }}">
                            <img src="{{ image.path.url }}" width="50px" height="40px"/>
                          </a>
                      </td>
                      <td>
                          <input type='text' name='image_name' value='{{ image.name }}' class="form-control">
                      </td>
                      <td class="rank">
                          <!--{{ image.rank }}-->
                          <input type='text' name='rank' value='{{ image.rank }}' class="form-control">
                          <input type='hidden' name='id' value='{{ image.id }}'>
                      </td>
                      <td class="operation">
                        <a href="{% url 'template:image_delete' id=image.id %}" class="btn btn-sm btn-danger"  id="deleteBtn{{ image.id }}">削除 {% fontawesome_icon 'trash'  %}</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>

                <div class="operation">
                    <p><button type="submit" class="btn btn-warning">{% fontawesome_icon 'save'  %} 更新する</button></p>
                </div>
            </div>

            <div id="dialog-confirm" title="テンプレート画像削除確認">
              <p><span class="ui-icon ui-icon-alert" ></span>このテンプレート画像を削除します。よろしいでしょうか?</p>
            </div>
        {% endif %}
    {% endif %}
    </form>

<script>
    $(document).ready(function () {
       //　モーダル初期設定
        $('#dialog-confirm').dialog({
            autoOpen: false,  // 自動でオープンしない
            modal: true,      // モーダル表示する
            resizable: false, // リサイズしない
            draggable: false, // ドラッグしない
            show: "clip",     // 表示時のエフェクト
            hide: "fade",      // 非表示時のエフェクト
            buttons: {
                "確認": function() {
                    location.href=target_url;
                },
                "閉じる": function() {
                    $( this ).dialog( "close" );
                }
            }
        });

        // .selecter クリック時にモーダル表示
        $("[id^=deleteBtn]").on("click",function(){
            target_url = $(this).attr("href");
            $('#dialog-confirm').dialog('open');
            return false;
        });
    });
</script>
{% endblock content %}

template/templates/template/upload.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}
{% load fontawesome %}
{% block title %}テンプレート画像登録{% endblock title %}

{% block content %}
<h3 class="page-header">テンプレート画像登録</h3>
<a href="{% url 'template:template_update' id=template.id %}" class="btn btn-default btn-sm">{% fontawesome_icon 'arrow-left'  %} 戻る </a>
  <form method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
<!--      {{ form|bootstrap_horizontal }}-->
        <section class="form-box">
            <fieldset>
                <p><span class="required">[*]は必須入力項目です。</span></p>
            {% for field in form %}
                {% if field.errors %}
                    <div class="control-group error">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">{{ field }}
                            <span class="help-inline">
                                {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="control-group">
                        <label class="control-label">{{ field.label }}<span class="required">[*]</span></label>
                        <div class="controls">{{ field }}
                            {% if field.help_text %}
                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
                <div class="operation">
                    <p><button type="submit" class="btn btn btn-success">{% fontawesome_icon 'save'  %} テンプレート画像を登録する</button></p>
                </div>
            </fieldset>
        </section>
  </form>

<script>
$(document).ready(function () {
    $('form input:file').uploadThumbs({
        position : 0,      // 0:before, 1:after, 2:parent.prepend, 3:parent.append,
                           // any: arbitrarily jquery selector
        imgbreak : true    // append <br> after thumbnail images
    });
})
</script>


{% endblock %}