api/urls.py
from rest_framework import routers
from .views import ImageViewSet, TemplateViewSet, TransactionViewSet

router = routers.DefaultRouter();
router.register(r'template', TemplateViewSet)
router.register(r'image', ImageViewSet)
router.register(r'transaction', TransactionViewSet)

myopencv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static

from api.urls import router as api_router

from .settings import MEDIA_ROOT, MEDIA_URL
from django.views.static import serve

urlpatterns = [
    # admin を有効にする
    url(r'^admin/', admin.site.urls),

    # template
    url(r'^template/', include('template.urls', namespace='template')),

    # API
    url(r'^api/', include(api_router.urls)),

    # link: http://stackoverflow.com/questions/34727928/django-1-10-urls-deprecation
    url(r'^data/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

template/urls.py
from django.conf.urls import url
from template import views


urlpatterns = [
    # テンプレート
    url(r'^$', views.template_list, name='template_list'),  # 一覧
    url(r'^create/$', views.template_update, name='template_create'),  # 登録
    url(r'^update/(?P<id>\d+)/$', views.template_update, name='template_update'),  # 修正
    url(r'^delete/(?P<id>\d+)/$', views.template_delete, name='template_delete'),  # 削除

    # 画像
    url(r'^update/(?P<id>\d+)/upload$', views.image_upload, name='image_upload'),  # 修正
    url(r'^image/delete/(?P<id>\d+)/$', views.image_delete, name='image_delete'),  # 削除

    #
    url(r'^transaction$', views.transaction_list, name='transaction_list'),  # 一覧
    url(r'^transaction/create/$', views.transaction_create, name='transaction_create'),  # 登録

]

template/templates/base.html
{% load staticfiles %}
{% load bootstrap %}
{% load fontawesome %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ja" }}">

<head>
<meta charset="UTF-8">
{% fontawesome_stylesheet %}
<title>{% block title %}物体マーチング{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static  'js/fancybox/jquery.fancybox.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- fancybox -->
<script src="{% static 'js/fancybox/jquery.fancybox.js' %}"></script>
<script src="{% static 'js/jquery.uploadThumbs.js' %}"></script>
    {% block extrahead %}{% endblock %}
</head>

<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'template:transaction_create' %}">{% fontawesome_icon 'eye'  %} 物体認識</a></i>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">物体マーチング <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'template:transaction_create' %}">マッチング実施</a></li>
                  <li><a href="{% url 'template:transaction_list' %}">マッチング履歴一覧</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'template:template_list' %}">テンプレート管理</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
        {% block content %}
          {{ content }}
        {% endblock %}
    </div> <!-- /container -->



</body>
</html>